name: GPT Translate

on:
  pull_request:
    paths:
      - 'src/content/local-docs/libs/**'

permissions: write-all

env:
  LANGUAGES: 'ru,ko,es,de,zh,fr'

jobs:
  prepare-inputs:
    runs-on: ubuntu-latest
    outputs:
      modified_library_readmes: ${{ steps.get-modified-files.outputs.modified_library_readmes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get modified files
        id: get-modified-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E 'src/content/local-docs/libs/.*/README\.md$' || echo "")

          # Prepare output with library names for matrix strategy
          JSON_OUTPUT=$(echo "$MODIFIED_FILES" | awk 'NF' | jq -R -c -s '
            split("\n") |
            map(select(length > 0)) |
            map(capture("src/content/local-docs/libs/(?<lib>[^/]+)/README\\.md").lib)
          ')

          echo "modified_library_readmes=$JSON_OUTPUT" >> $GITHUB_OUTPUT

  translations:
    needs: prepare-inputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: ${{ fromJson(needs.prepare-inputs.outputs.modified_library_readmes) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Prepare inputs for ${{ matrix.library }}
        id: prepare-inputs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARY: ${{ matrix.library }}
        run: |
          LIBRARY_README="src/content/local-docs/libs/${LIBRARY}/README.md"

          echo "Processing library: $LIBRARY"
          echo "README file: $LIBRARY_README"

          OUTPUT_FILES=""
          for LANGUAGE in $(echo "${{ env.LANGUAGES }}" | tr ',' ' '); do
            OUTPUT_FILES="$OUTPUT_FILES src/content/local-docs/libs/${LIBRARY}/README-${LANGUAGE}.md"
          done

          echo "Output files: $OUTPUT_FILES"

          echo "input_files=$LIBRARY_README" >> $GITHUB_OUTPUT
          echo "output_files=$OUTPUT_FILES" >> $GITHUB_OUTPUT
      - name: Run translations
        uses: dgaponov/gpt-translate@master
        with:
          provider: 'openrouter'
          apikey: ${{ secrets.OPENROUTER_API_KEY }}
          model: 'x-ai/grok-4-fast:free'
          inputFiles: ${{ steps.prepare-inputs.outputs.input_files }}
          outputFiles: ${{ steps.prepare-inputs.outputs.output_files }}
          languages: ${{ env.LANGUAGES }}
          prompt: |
            Please translate the README source file to {targetLanguage}. \
              Make the translation sound as natural as possible. \
              Keep the HTML snippet with the language options in the same place as in the source file. \
              Do not translate the first line in the source file if it looks like the name of the library. \
              For example, don't translate @gravity/uikit or Axios Wrapper - they need to be left in place.
