name: Update translations

on:
  workflow_dispatch:
#  schedule:
#    - cron: 5,10,15,20,25,30,35,40,45,50,55 * * * *

permissions: write-all

env:
  LANGUAGES: 'ru ko es de zh fr' # Supported languages separated by space (spaces are important)

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run translations
        uses: dgaponov/gpt-translate@master
        with:
          provider: 'openrouter'
          apikey: ${{ secrets.OPENROUTER_API_KEY }}
          model: 'x-ai/grok-4-fast:free'
          inputFiles: 'public/locales/en/*.json'
          outputFiles: 'public/locales/ru/*.json public/locales/ru/ko.json public/locales/ru/es.json public/locales/ru/de.json public/locales/ru/zh.json public/locales/ru/fr.json'
          languages: ${{ env.LANGUAGES }}
          prompt: |
            Please translate the json source file to {targetLanguage}. \
              Make the translation sound as natural as possible. \
              Do not translate the library name in the source file if it looks like the name of the library. \
              For example, don't translate @gravity/uikit or Axios Wrapper - they need to be left in place.
